### ISSUE TITLE
Unexpectedly large amount of log messages

### ISSUE THREAD

**Issue by enveeed** [TheSilentPro/HeadDB#48]
**Describe the bug**
Recently updated to rc6 and I'm receiving way more log messages from this plugin than before. The update interval is set to one hour, so I'm not entirely sure what is going on but it fills up my log files rather quickly and buries important other log events.

**Information**
Plugin Version: `5.0.0-rc.6`
Server Version: Paper 542 (1.19.4)
Client Version: n.a.

**Screenshots**
![Screenshot from 2023-06-08 19-53-38](https://github.com/TheSilentPro/HeadDB/assets/25058915/634f0e0d-d3a1-4716-a16e-0c7f52b4f1cf)

**Comment by TheSilentPro** [comment]
will fix in a few hours, send me your config.yml though

**Comment by enveeed** [comment]
```YAML
# When enabled heads will be fetched from startup, otherwise when the /hdb command is ran
fetchStartup: false

# When enabled, heads will be fetched async (Startup Only)
asyncStartup: false

# If the cached heads are older than these amount of seconds, the plugin will refresh the database
refresh: 3600

# If local heads should be enabled. Only keeps track of joined players when enabled!
localHeads: true

# Economy options
economy:
  enable: false
  cost:
    alphabet: 100
    animals: 100
    blocks: 100
    decoration: 100
    food-drinks: 100
    humans: 100
    humanoid: 100
    miscellaneous: 100
    monsters: 100
    plants: 100
    local: 1000

# UI customization options.
ui:
  category:
    # Head categories. You can use item: instead of head: here, but AIR is not supported.
    alphabet:
      location: 20
      head: 1788
    animals:
      location: 21
      head: 5741
    blocks:
      location: 22
      head: 8624
    decoration:
      location: 23
      head: 11046
    food-drinks:
      location: 24
      head: 17442
    humans:
      location: 29
      head: 19361
    humanoid:
      location: 30
      head: 28320
    miscellaneous:
      location: 31
      head: 32746
    monsters:
      location: 32
      head: 34819
    plants:
      location: 33
      head: 37278
    # Meta categories, used for UI elements. AIR is not supported. You can use head: instead of item: here.
    favorites:
      location: 39
      item: BOOK
    search:
      location: 40
      item: DARK_OAK_SIGN
    local:
      location: 41
      item: COMPASS
    # Item used to fill unused slots in the categories menu. AIR is supported. You can use head: instead of item: here.
    fill:
      item: BLACK_STAINED_GLASS_PANE

# Debug Mode
debug: false
```
